name: lms_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  provider: ^6.1.4
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.1.1
  vimeo_player_flutter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
